const codes = {
    SUCCESS: 'SUCCESS',
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNPROCESSED_ENTITY',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
    MISSING_TOKEN: 'MISSING_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_PARAMS: 'INVALID_PARAMS',
    RESOURCE_EXIST: 'RESOURCE_EXIST',
    USER_EXIST: 'USER_EXIST',
    USER_NOT_FOUND: 'USER_NOT_FOUND'
};

export default codes;